org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.176
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=textanimator
mod_version=3.2.3
mod_group_id=snownee.textanimator
archives_base_name=TextAnimator
release_type=release
